# Matrices


## Import

In [2]:
import numpy as np

## Matrix as a `NumPy` array

Everything in `NumPy` is an array. A matrix is also an array. Let us create a simple matrix:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Adding two matrices

Let us now add the following matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} + \textbf{B}  = \begin{bmatrix}
6 & 8\\
10 & 12
\end{bmatrix}
$$

In `NumPy`:

In [36]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A+B)

[[ 6  8]
 [10 12]]


## Scaling a matrix

Scaling a matrix is nothing but element-wise multiplication:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

then,

$$
3 \textbf{M} = \begin{bmatrix}
3 & 6 & 9\\
12 & 15 & 18\\
21 & 24 & 27
\end{bmatrix}
$$

In `NumPy`:

In [41]:
A = np.arange(1,10).reshape(3,3) # you will learn about this step in line 16 and 17
print(3*A)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Element-wise multiplication of matrices

Consider two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
$$

The element-wise product is given by $\textbf{A} \odot \textbf{B}$:

$$
\textbf{C} = \textbf{A} \odot \textbf{B} = \begin{bmatrix}
5 & 12\\
21 & 32
\end{bmatrix}
$$

In `NumPy`:

In [42]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A*B)

[[ 5 12]
 [21 32]]


## Element-wise functions of matrices

Given a matrix, we sometimes would want to apply a function to every element of the matrix. We will consider two examples.

### Example-1

For example, we may want to take the absolute value of all the elements. Let us say $f(x) = |x|$, then:

$$
\mathbf{A} = \begin{bmatrix}
-1 & 2\\
-3 & -4
\end{bmatrix}
$$

then:

$$
\begin{bmatrix}
f(-1) & f(2)\\
f(-3) & f(-4)
\end{bmatrix} =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}
$$

In `NumPy`, this becomes:

In [ ]:
x = np.array([[-1,2],[-3,-4]])
y = np.abs(x)
y

array([[1, 2],
       [3, 4]])

### Example-2

We might want to square each element of the matrix. If $\textbf{A}$ is a matrix, then $\textbf{B}$ could be defined element-wise as follows:

$$
B_{ij} = A_{ij}^2
$$

Let us compute $\mathbf{B}$ for the following matrix:

$$
\mathbf{A} = \begin{bmatrix}
1 & \sqrt{2}\\
\sqrt{3} & 2
\end{bmatrix}
$$

In `NumPy`:

In [44]:
A = np.array([[1 , np.sqrt(2)],[np.sqrt(3),2]]) # np.sqrt() is a mathematical tool for square root of a number
B = A**2
print(B) # using np.sqrt() will convert the values inside the matrix into float type by default.

[[1. 2.]
 [3. 4.]]


## Transpose of a matrix

Given a matrix $\textbf{M}$:

$$
\textbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

then, its transpose $\textbf{M}^{T}$ is:

$$
\textbf{M}^{T} = \begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([[1,2,3],[4,5,6]])
y = np.transpose(M)
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
y = M.T # better option than np.transpose
y

array([[1, 4],
       [2, 5],
       [3, 6]])

## Shape and dimension of a matrix

Matrices are "two dimensional" arrays. So all matrices in `NumPy` have array-dimension equal to two. The shape of the `NumPy` array gives what we usually call the dimension of the matrix in the linear algebra sense.

Explore these two ideas for:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
M = np.array([[1,2,3],[4,5,6]])
print(M.shape) # (rows,column,)
print(M.ndim) # 2-Dimensional array

(2, 3)
2


## Vectors as matrices

Each vector can be viewed as a matrix. Column vectors are matrices of shape $(d, 1)$. Row vectors are matrices of shape $(1, d)$. Let us look at how NumPy treats both these cases:


In [ ]:
X = np.array([1,2,3])
print(X)

Y = np.array([[1],[2],[3]])
print(Y)

print(X.shape , Y.shape)
print(X.ndim , Y.ndim)

[1 2 3]
[[1]
 [2]
 [3]]
(3,) (3, 1)
1 2


## Products involving matrices and vectors

We will look at the following products:
- matrix - matrix
- matrix - vector
- vector - matrix
- vector - vector

### Product of two matrices

Given two matrices:

$$
\textbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}, \textbf{B} = \begin{bmatrix}
6 & 7\\
8 & 9\\
10 & 11
\end{bmatrix}
$$

then,

$$
\textbf{C} = \textbf{A} \times \textbf{B} = \begin{bmatrix}
52 & 58\\
124 & 139
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
A @ B

array([[ 58,  64],
       [139, 154]])

### Product of a matrix and a (column) vector

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{Ax}$ is given by:

$$
\mathbf{C} = \mathbf{A x} = \begin{bmatrix}
44\\
107\\
170
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([6,7,8])
A @ X # here even if you don't give the transposed matrix , it will automatically do the transpose and give you the ccorrect output.

array([ 44, 107, 170])

### Product of a (row) vector and a matrix

Given the matrix $\mathbf{A}$ and the vector $\mathbf{x}$:

$$
\mathbf{A} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}, \mathbf{x} = \begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{A}$ is given by:

$$
\mathbf{C} = \mathbf{x}^T \mathbf{A} = \begin{bmatrix}
90 & 111 & 132
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([6,7,8])

X @ A # here @ can even convert the vector X into a matrix with 1 row and then give you the output.

array([ 90, 111, 132])

### (Inner) Product of a (row) vector and a (column) vector

The product of a row vector and a column vector is nothing but the usual dot product:

$$
\mathbf{x}^T = \begin{bmatrix}
1 & 2 & 3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4\\
5\\
6
\end{bmatrix}
$$

The product $\mathbf{x}^T \mathbf{y}$ is then:

$$
\mathbf{x}^T \mathbf{y} = 32
$$

In `NumPy`:

In [ ]:
# you can again use @ here , it will give you the required answer

### (Outer) Product of a (column) vector and a (row) vector

The product of a column vector and a row vector is an outer product:

$$
\mathbf{x} = \begin{bmatrix}
1\\
2\\
3
\end{bmatrix}, \quad
\mathbf{y} = \begin{bmatrix}
4 & 5 & 6
\end{bmatrix}
$$

The product $\mathbf{x} \mathbf{y}^T$ is then:

$$
\mathbf{x} \mathbf{y}^T = \begin{bmatrix}
4 & 5 & 6\\
8 & 10 & 12\\
12 & 15 & 18
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
# used in co variance matrix

x = np.array([1,2,3])
y = np.array([4,5,6])

np.outer(x,y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

## Matrix of zeros

In many algorithms, we might have to initialize a matrix with zeros. For example, consider a $2 \times 4$ matrix:

$$
\mathbf{M} = \begin{bmatrix}
0 & 0 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Matrix of ones

Similar to a matrix of zeros, we can come up with a matrix of ones.

$$
\mathbf{M} = \begin{bmatrix}
1 & 1\\
1 & 1\\
1 & 1
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Identity matrix

Often, we might have to deal with identity matrices. A $3 \times 3$ identity matrix is as follows:

$$
\mathbf{I} = \begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$

In `NumPy`:

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Diagonal matrices

Another special kind of matrix. Let us create the following matrix:

$$
\mathbf{D} = \begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 4
\end{bmatrix}
$$

In `NumPy`:

In [3]:
np.diag([1,2,3,4]) #takes in parameter as the diagonal elements.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Indexing and Slicing

Just like lists in Python, `NumPy` arrays can be indexed and sliced. Slicing is useful if we want to work with a portion of an array. We will look at some examples.

### Example-1: Row-slice

We will extract the third row of the matrix $\mathbf{M}$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
7 & 8\\
9 & 10
\end{bmatrix}
$$



In `NumPy`:

In [16]:
V = np.arange(1,11) # it can't shape a 1-D array of prime number of elements to any new shape.
V = V.reshape(5,2) # will make our life simpler by converting an array to required shape.
# if you set any one parameter to -1 in reshape() funtion will automatically compute the valid value of that particular parameter.
V

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
print(V[2]) #for rows you can just simply apply the logic of list indexing method to get your answer.

[5 6]


### Example-2: Column slice

Let us now extract the second column of the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{bmatrix}
$$

In `NumPy`:

In [18]:
V = np.arange(1,10).reshape(3,3) # you can attach two functions to make your code shorter.
V

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(V[1,2]) # this simply means traversing to 2nd row and 3rd column
print(V[:,1]) # adding a colon means getting all the elements related to that parameter.

6
[2 5 8]


### Example-3: Submatrix slice

Now, we want to extract the $2 \times 2$ submatrix colored in blue from $M$:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & \color{blue}7 & \color{blue}8\\
9 & 10 & \color{blue}{11} & \color{blue}{12}\\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In `NumPy`:

In [23]:
V = np.arange(1,17).reshape(4,4)
V

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
# In line 22 , we just used 1 number for input in row and column , but we can give a series
# of rows and columns as input which will enable us to use submatrix slice

V[1:3 , 2:4] #here we used '1:3' to specify that we wan't 2nd to 3rd row. we used '2:4' to
# specify that we want from column 3 to 4 . And hence u can see the result.

array([[ 7,  8],
       [11, 12]])

## Matrix algebra

There are several important matrix operations that we will list down here. The `np.linalg` module helps us perform these operations effortlessly.

## Rank, Inverse

We can get the rank of a matrix and its inverse as follows:

In [28]:
V[1,2]=22  # changed an element in previous matrix , as that was a singular matrix , whose inverse is not possible.

# rank

print(np.linalg.matrix_rank(V))

# inverse

print(np.linalg.inv(V))

3
[[ 3.75299969e+14 -6.66666667e-02 -1.12589991e+15  7.50599938e+14]
 [-5.62949953e+14  6.66666667e-02  1.68884986e+15 -1.12589991e+15]
 [-5.55555556e-02  6.66666667e-02  3.33333333e-02 -4.44444444e-02]
 [ 1.87649984e+14 -6.66666667e-02 -5.62949953e+14  3.75299969e+14]]


### Pseuodoinverse

The pseudoinverse $\mathbf{M}^{\dagger}$ of a matrix $\mathbf{M}$ with real entries satisfies the following properties:

- $\mathbf{M} \mathbf{M}^{\dagger} \mathbf{M} = \mathbf{M}$
- $\mathbf{M}^{\dagger} \mathbf{M} \mathbf{M} = \mathbf{M}^{\dagger}$
- $\mathbf{M} \mathbf{M}^{\dagger}$ is symmetric
- $\mathbf{M}^{\dagger} \mathbf{M}$ is symmetric

Let us go ahead and verify this for the following matrix:

$$
\mathbf{M} = \begin{bmatrix}
1 & 2 & 3\\
3 & 6 & 9
\end{bmatrix}
$$

Note: For a complete list of properties of the pseudoinverse, check out this [link](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Definition).

In [31]:
M = np.array([[1,2,3],[3,6,9]])
print(np.linalg.matrix_rank(M))
print(np.linalg.pinv(M)) # pseudo-inverse

1
[[0.00714286 0.02142857]
 [0.01428571 0.04285714]
 [0.02142857 0.06428571]]


## Eigenvalues and Eigenvectors

Given a symmetric matrix $\mathbf{M}$ let us find its eigenvalues and eigenvectors:

$$
\mathbf{M} = \begin{bmatrix}
1 & 0 & -3\\
0 & 5 & 2\\
-3 & 2 & 8
\end{bmatrix}
$$

In [33]:
M = np.array([[1,0,-3],[0,5,2],[-3,2,8]])

eigen_values , eigen_vector = np.linalg.eigh(M) # linal.eigh() returns two values , the 1st one is eigne values and 2nd is corresponding eigen vectors.

print(eigen_values , eigen_vector)

[-0.20942046  4.36588492  9.84353554] [[ 0.91805853  0.26010485 -0.2991889 ]
 [-0.14209114  0.92042494  0.36418131]
 [ 0.37010626 -0.29182767  0.88196257]]


## SVD

We can compute the singular value decomposition of a matrix $\mathbf{M}$ as:

$$
\mathbf{M} = \mathbf{U} \boldsymbol{\Sigma} \mathbf{V}^T
$$

Here, the symbols have their usual meanings.

In [34]:
np.linalg.svd? # using '?' will help you to know about np.linalg.svd() . U will notice that it gives three return values. Please refer to the doc and learn about SVD to understand about the return values